### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by OmerTirosh**
Update code to work with the last version of beats

### CODE REVIEW

**Comment by raboof** [comment]
Thanks for looking into this!

Unfortunately travis seems to fail to find these new dependencies. Should they be fetched in a different way?

**Comment by OmerTirosh** [comment]
Hi, 
Honestly, I am new to travis-ci and don't know how the travis fetches the dependencies, and how to write tests.
Beats changed the dependency management system to 'go mod' instead of 'govendor' and the module name is github.com/elastic/beats/v7. more information at: [Go Modules](https://github.com/elastic/beats/commit/95626b8f1690344312c0831ab2bdcbccffe4d089#diff-dce5417e4bb2e42266e32610d228789c974ee2b4b814cf474568f049be034df1)
Can you take a look at this?

Thank you very much!

**Comment by raboof** [comment]
> Can you take a look at this?

Added it to my TODO list, but that one is long, so realistically I might not get to it any time soon, sorry...

**Comment by oOKevinOo** [comment]
hello bro，how can i fetch the lastiest version to work with last version of beats,could you commit the lateiest code?

**Comment by raboof** [comment]
> hello bro，how can i fetch the lastiest version to work with last version of beats,could you commit the lateiest code?

Unfortunately I don't feel comfortable merging this until we figure out how to build it on CI.

**Comment by raboof** [comment]
I got it to work by adding a go.mod. Could you test that with https://github.com/OmerTirosh/beats-output-http/pull/3 beats-output-http still works for you @OmerTirosh ? If so we can merge :shipit:

**Comment by raboof** [comment]
@OmerTirosh I see you merged my proposal into your PR - that's great!

Do you plan to do any more testing or do you think this is good to go?

**Comment by OmerTirosh** [comment]
@raboof We tested it in our team and it didn't gave us any problems.
One more thing, we should refractor the logging system, to make it more indicative.

Thank you for the help with the testing!!

**Comment by raboof** [comment]
> We tested it in our team and it didn't gave us any problems.

Great, thanks!

> One more thing, we should refractor the logging system, to make it more indicative.

I'm not using beats-output-http myself at the moment, so I'm not planning any improvements at this time, but I'd be happy to include your contributions!

**Pull request merged**
